# Generated by Django 2.1.2 on 2018-10-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20181026_1822'),
        ('users', '0002_history_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_disipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.disipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
