# Generated by Django 2.1.2 on 2018-10-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_disipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
