# Generated by Django 2.1.2 on 2018-10-26 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fami',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.family'),
            preserve_default=False,
        ),
    ]
