# Generated by Django 2.1.2 on 2018-10-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20181026_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(default='media/images/logo-Copy.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
