# Generated by Django 2.1.2 on 2018-10-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20181026_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disipline',
            name='image',
        ),
    ]
