# Generated by Django 2.1.2 on 2018-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_disipline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disipline',
            name='image',
            field=models.FileField(default='images/2jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
