# Generated by Django 2.1.2 on 2018-10-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_disipline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vues',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
