# Generated by Django 2.1.2 on 2018-10-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_qst_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qst',
            name='image',
        ),
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.FileField(default='akr.jpg', upload_to='images/'),
        ),
    ]
